# Generated by Django 5.2.5 on 2025-08-27 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliatecommission',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=40.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='affiliatecommission',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='affiliateprofile',
            name='affiliate_code',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
